### ISSUE TITLE
Color Picker is not properly styled when clearButton is set

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-theme-default#103]
- [x] Correct stylization of 'no color' indication:
- diagonal line should use error color;
- diagonal line should be horizontally flipped 

- [x] Text input width and height should be expanded

![screen shot 2017-01-13 at 2 02 07 pm](https://cloud.githubusercontent.com/assets/16577622/21930082/ca602268-d99c-11e6-957c-4460df56b5f8.png)

- [x] Clear button is not styled properly
- [x] 'Apply' and 'Cancel' Button - aligned center
![colorpicker](https://cloud.githubusercontent.com/assets/13251479/22021962/8c25ec60-dcc8-11e6-8175-0c2a9f97bb2c.png)

Design Preview
![colorpicker-default-v2](https://cloud.githubusercontent.com/assets/16577622/22030359/1197d396-dce6-11e6-9f56-ee4021ed4929.png)

**Comment by joneff** [comment]
Fixed by c53ba3f.

I took the liberty to center align the clear button when used in conjunction with `preview: false`. Also, the "apply" and "cancel" buttons are not stretched, but rather center aligned. That may be fixed at a later stage.
