### ISSUE TITLE
Invalid styles should take ng-touched in consideration

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-theme-default#127]
Currently we only check ng-invalid e.g. `.k-textbox.ng-invalid`, when applying the styles, which results in displaying the _invalid_ styling on initial form load. Maybe we should consider checking both invalid and touched states (not sure about pristine)?

cc @rusev @ggkrustev @tsvetomir

**Comment by gyoshev** [comment]
Seems like a good idea in our current editing demo, when form posting is disabled when the form is invalid. My only concern is that there is no indication that the form is invalid, if it is submitted without touching any of the fields. Clicking `Save` in the example below will not indicate that the form is not valid:

![image](https://cloud.githubusercontent.com/assets/90405/22108615/abdb7602-de5c-11e6-9397-7fe28d341cac.png)

See [this plunkr snippet](http://plnkr.co/edit/RprNRj6XlZPuuCAPqZf8?p=preview) and try to add a new record. Should we support this scenario, or is disabling the submit button the better UX? Ideally, clicking submit in that scenario should mark the inputs as invalid, and show the validation messages. Is that possible with the Angular validation?

**Comment by gyoshev** [comment]
Since the Angular documentation [recommends looking at these properties](https://angular.io/docs/ts/latest/cookbook/form-validation.html#!#why-check-_dirty_-and-_touched_-), the above scenario seems irrelevant.
