### ISSUE TITLE
Missing styles for k-bare-button in toolbar

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-theme-default#144]
**k-bare-button**
normal - color: inherit; opacity 0.7
hover - color: inherit; opacity 1
active - color: inherit; opacity 1
focused - background: currentColor; opacity 12% / 26% (accent)
![k-bare-button-states](https://cloud.githubusercontent.com/assets/16577622/22071090/bb3909ea-dda6-11e6-9f44-53544080d9ef.png)

**Comment by joneff** [comment]
fixed by 8e1eb1313c9dc461d8c1b3a3a64c71cd216de846
