### ISSUE TITLE
K1 Grid filter row autocomplete discrepancies

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-theme-default#148]
Opening the filter row autocomplete displays a gap between the input and the list

![dd1](https://cloud.githubusercontent.com/assets/730205/22107349/ed94a1e2-de55-11e6-8111-ef75a1547077.png)

Additionally after filtering, the filter icon is hidden and only the clear icon is displayed. They should both be visible. This is also applicable to the other input components in the filter row.

![dd2](https://cloud.githubusercontent.com/assets/730205/22107364/07b9a248-de56-11e6-9524-c86b1514792f.png)

**Comment by inikolova** [comment]
The issue can be reproduced with the new default theme
