### ISSUE TITLE
Focus over selected item is not prominent enough

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-default#150]
Currently in the dropdowns when you move the focus over the selected item it can not be clearly distinguished 

cc @yordanov

**Comment by sigVince** [comment]
Also, the color of the shadow depends on the color of the border, would be great to be able to change it via a variable.

**Comment by inikolova** [comment]
Seems similar to this one - https://github.com/telerik/kendo-angular-dropdowns/issues/104

**Comment by inikolova** [comment]
@sigVince , there is a **$list-item-focused-shadow** variable which defines the focused item box-shadow
