### ISSUE TITLE
Helper classes for styling font icons

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#154]
Let's add helper styles to:
- [x] set font-size - sm/md/lg
- [x] flip icons - flip-horizontal/flip-vertical/flip-horizontal-vertical

**Comment by joneff** [comment]
Helper classes for font-icon already exists: https://github.com/telerik/kendo-theme-default/blob/master/scss/common/_icons.scss#L43-L47

I've added helper classes for horizontal / vertical flipping -- `k-flip-h` and `k-flip-v`.
