### ISSUE TITLE
 Inconsistent Editor indent/outdent icons in RTL

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-default#155]
### Bug report
 Inconsistent Editor indent/outdent icons with Default v2 skin in RTL mode

### Reproduction of the problem
http://demos.telerik.com/kendo-ui/editor/right-to-left-support

### Current behavior
Indent/Outdent icons are not consistent with the rest of the skins
https://www.screencast.com/t/6Lf1NSlleL

### Expected/desired behavior
Indent/Outdent icons arrows position match the rest of the skins
![image](https://user-images.githubusercontent.com/6614183/28266389-3fedcc28-6afd-11e7-8063-2a29674eb977.png)

Possible solution would be to apply the following style: transform: scaleX(-1);

### Environment

* **Kendo UI version:** Q1 2017
* **Browser:** [all]

**Comment by Dimitar-Goshev** [comment]
The issue is fixed
