### ISSUE TITLE
Incompatible units error occurs when the SCSS from the Default Theme is used with Bootstrap.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-theme-default#159]
Incompatible units error occurs when the SCSS from the Default Theme is used with Bootstrap.

Error:  Incompatible units: 'px' and 'rem'.

If styles аре loaded from the dist folder, there are no errors in the bundle.

**Comment by gyoshev** [comment]
The issue has been resolved with the above commit.
