### ISSUE TITLE
Ensure compatibility with Bootstrap variables

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-theme-default#175]
The issue appears often (#159 and thread 1086556): the theme may not always be compatible with the Bootstrap variables or their types. A good way of ensuring compatibility is adding a check to the build scripts, so that it can be verified on every commit.

**Comment by szavoda** [comment]
I noticed that there is still an issue with the current compatibility that was not resolved in issue #159.  I wasn't sure if I should open a new bug or not...  The error is as follows:

ERROR in ./~/css-loader?sourcemap!./~/postcss-loader!./~/sass-loader?sourcemap!./src/scss/style.scss
Module build failed:
$input-height:                   (($font-size-base * $line-height-base) + ($input-padding-y * 2)) !default;
                                  ^
      Incompatible units: 'px' and 'rem'.
      in D:\Dev\Jsa\2017\Jsa.Admin\src\scss\bootstrap_src\_variables.scss (line 349, column 36)
 @ ./src/scss/style.scss 4:14-187
 @ multi styles

**Comment by gyoshev** [comment]
@szavoda I believe this may happen if the Kendo styles are included before the Bootstrap ones, thus overriding the default Bootstrap variables. Perhaps reversing the order (including Bootstrap before Kendo) will resolve the problem?

**Comment by szavoda** [comment]
@gyoshev I moved it to the end of the file and still get an error, but it is different.  The error points to the "input" scss:

ERROR in ./~/css-loader?sourcemap!./~/postcss-loader!./~/sass-loader?sourcemap!./src/scss/style.scss
Module build failed:
undefined
                  ^
      Incompatible units: 'px' and 'rem'.
      in D:\Dev\Jsa\2017\Jsa.Admin\node_modules\@progress\kendo-theme-default\scss\input\_layout.scss (line 99, column 20)
 @ ./src/scss/style.scss 4:14-187
 @ multi styles

**Comment by joneff** [comment]
@szavoda I think we fixed all occurrences of mixed variables for the default theme. Can you double check that?

**Comment by szavoda** [comment]
Sorry - I never got the notification - themes look good now!

**Comment by praneethw** [comment]
I seem to have a similar issue, and hence was not sure to open a new bug. I am using,
**"@progress/kendo-theme-default": "2.31.4",
"bootstrap": "^4.0.0-alpha.6",**

WebPack loaders,
**loaders: ['style-loader', 'css-loader', 'resolve-url-loader', 'sass-loader']**

Upon compilation I receive the error,
**./~/css-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js!./Client/vendors.scss
Module build failed: 
undefined
                      ^
      0.05357em*rem/px isn't a valid CSS value.
      in C:\Projects\src\Optimizer.Web\node_modules\@progress\kendo-theme-default\scss\input\_layout.scss (line 254, column 24)
 @ ./Client/vendors.scss 4:14-163 13:2-17:4 14:20-169
 @ multi webpack-hot-middleware/client?path=%2F__webpack_hmr ./Client/vendors.ts ./Client/vendors.scss**

If I swap between either bootstrap or kendo-theme-default to the dist/ .css file the compilation succeeds. What would be the solution for working with both libraries .scss versions?

**Comment by gyoshev** [comment]
@praneethw the error you describe should be solved in `2.31.5`. This issue has introduced a build step that verifies that the SCSS files are compatible with the Bootstrap SCSS.

Please note that the Bootstrap version is [pinned to a commit after alpha.6](https://github.com/telerik/kendo-theme-default/blob/master/package.json#L57). We plan on releasing compatibility with the public beta [once it is released](https://github.com/twbs/bootstrap/milestone/41).
