### ISSUE TITLE
Add focused state styling for the Grid

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-default#178]
For the requirements of the kb navigation in the grid, the k-state-focused class and styling is needed. Will we handle this with class (the classic approach :)) or we can think of something else?

cc @gyoshev

**Comment by gyoshev** [comment]
We always try to handle issues with class 😁 

It is best if we add the `k-state-focused` class for the grid, in order to keep the same rendering that works in the jQuery grid.
