### ISSUE TITLE
Wrong dialog header dimension, styles, color states and button position 

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-theme-default#179]
- [x] dialog metrics
- [x] header bg color
- [x] header metrics
- [x] title font size
- [x] primary action text color
- [x] close button - hover state should increase the icon, wrong opacity state on hover;

![untitled-1](https://cloud.githubusercontent.com/assets/16577622/22468215/2d68b1fe-e7d0-11e6-9613-7f616606e243.png)

Design:
https://github.com/telerik/kendo-ux/blob/master/components/dialog.psd

**Comment by joneff** [comment]
The only thing left is "position of primary action", but that's related to configuration within the theme builder app.

I've extracted the item and moved it to the appropriate repo.

**Comment by joneff** [comment]
Fixed by 1bda0423eb2175d36dfb42aa4cbb093c01977f57
