### ISSUE TITLE
Add styles for RTL support

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-theme-default#185]
On top of [#96](https://github.com/telerik/kendo-angular/issues/96) we will have to add component specific styles for RTL support. Feel free to add additional components to the list if styling is needed.

State of readiness:
- [x] @progress/kendo-angular-dropdowns
- [x] @progress/kendo-angular-grid
- [x] @progress/kendo-angular-upload

cc @gyoshev @yordanov @inikolova

**Comment by tsvetomir** [comment]
The clear buttons of the ComboBox and the MultiSelect are incorrectly positioned:
http://kendobuild/kendo-angular-ui/components/dropdowns/rtl/

![image](https://cloud.githubusercontent.com/assets/247917/24293981/16bddd6c-109d-11e7-9841-c18e3aaabe09.png)

**Comment by inikolova** [comment]
This is a known issue (https://github.com/telerik/kendo-theme-default/issues/261) - it will be fixed soon
