### ISSUE TITLE
Focus right border is missing in Grid

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-default#194]
Can be reproduced with grouped grid with locked columns on the cell that is the right most for the locked content.
![screen shot 2017-02-13 at 2 55 23 pm](https://cloud.githubusercontent.com/assets/4188451/22884220/7b854e48-f1fc-11e6-930b-ede2630f7f59.png)

**Comment by inikolova** [comment]
Related to this issue -> https://github.com/telerik/kendo-angular-grid/issues/94
