### ISSUE TITLE
Default height for group footer

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-default#204]
Maybe we can set a default height for the group footer in the Angular Grid, which will prevent some issues with the rendering. 

The current behavior can be seen [here](http://plnkr.co/edit/uNa2YLTGysjHNtwuhC1I?p=preview)

cc\\ @rkonstantinov @gyoshev

**Comment by inikolova** [comment]
Height should be set to **k-footer-template** actually
