### ISSUE TITLE
Icon button is higher than a regular one

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#218]
![icon-button](https://cloud.githubusercontent.com/assets/1118895/23116560/c558d7cc-f753-11e6-9742-e8eaaa006a6c.png)

**Comment by joneff** [comment]
@yordanov can you provide a link with that screenshot?

**Comment by yordanov** [comment]
http://www.telerik.com/kendo-angular-ui/components/buttons/button/

**Comment by joneff** [comment]
See https://github.com/telerik/kendo-theme-default/issues/220#issuecomment-281053309

There is a difference between how `height` and `line-height` are treated. Thus you have difference of 1 pixel in height. The correct height is on the icon button

**Comment by inikolova** [comment]
This issue has been already addressed
