### ISSUE TITLE
Grid sortable+filterable header problems in IE/Edge

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-theme-default#219]
The header titles and filter icons in filterable and sortable Grid are displaced increasing the header height. Observable in IE 11/Edge.

Dojo: http://dojo.telerik.com/equlO

Possible fix: 
```
    .k-grid-header th.k-header > .k-link {
        display: inline;
    }
```

**Comment by IanMuirhead** [comment]
@theOrlin Any idea on the timeline for this fix?  This one is particularly of interest for me as we are running into it.

**Comment by theOrlin** [comment]
@IanMuirhead The plan is to have this fixed for the next major release. You can try the suggested fix in the meanwhile. Let us know if you encounter any issues with it.

**Comment by IanMuirhead** [comment]
@theOrlin It helps - but I wouldn't consider it a fix.

IE11
<img width="432" alt="screen shot 2017-07-19 at 11 18 30 am" src="https://user-images.githubusercontent.com/884395/28382821-3e43be3c-6c74-11e7-8670-4d8ecc89b5c1.png">

Chrome
<img width="586" alt="screen shot 2017-07-19 at 11 19 53 am" src="https://user-images.githubusercontent.com/884395/28382820-3e315620-6c74-11e7-8f28-d788ad564c7d.png">

**Comment by IanMuirhead** [comment]
The following code seemed to sort it out for myself. I'm happy to raise a PR with the changes.

```
.k-grid-header th.k-header > .k-link {
    margin-right: 0.7em;
}

.k-grid-header .k-grid-filter, 
.k-grid-header .k-header-column-menu {
    position: absolute;
    right: 0;
    top: 0;
    float: none;
}

.k-grid th {
    padding: 0.7em 0.6em;
}

.k-grid-header .k-header {
    vertical-align: initial;
}
```

Chrome
<img width="714" alt="screen shot 2017-07-19 at 11 55 48 am" src="https://user-images.githubusercontent.com/884395/28384457-aab66f38-6c79-11e7-90b3-d3c5cfb5e826.png">

IE
<img width="702" alt="screen shot 2017-07-19 at 11 59 33 am" src="https://user-images.githubusercontent.com/884395/28384489-caabce6e-6c79-11e7-9400-8e4dac095d8f.png">
