### ISSUE TITLE
Icon in text button is not vertically centered

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#220]
![icon-in-button](https://cloud.githubusercontent.com/assets/1118895/23117142/ffcec13e-f756-11e6-99aa-54a94b36404c.png)

http://www.telerik.com/kendo-angular-ui/components/buttons/button/

Applies for a buttongroup  too.

http://www.telerik.com/kendo-angular-ui/components/buttons/buttongroup/

**Comment by joneff** [comment]
The issue is related to the demos using an older version of theme-default. Namely the issue is related to having a `line-height` property calculated with 5 digit precision, instead of 8 or more. In terms, the `line-height` is calculated to be 19 pixels instead of 20 pixels.

**Comment by inikolova** [comment]
This issue has been already addressed
