### ISSUE TITLE
Icons in splitbutton popup are vertically misaligned

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#222]
![icon-vertical-misalign](https://cloud.githubusercontent.com/assets/1118895/23117337/e94a2c7c-f757-11e6-943e-2b89d83f6fac.png)

http://www.telerik.com/kendo-angular-ui/components/buttons/splitbutton/

**Comment by joneff** [comment]
See https://github.com/telerik/kendo-theme-default/issues/220#issuecomment-281053309

The rest is related to `.k-list .k-item` not being flex container.
