### ISSUE TITLE
Missing focus state for MaskedTextBox and NumericTextBox

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#223]
![numeric-mask](https://cloud.githubusercontent.com/assets/1118895/23125509/beea8b20-f77a-11e6-9982-360b1a37584e.png)

http://www.telerik.com/kendo-angular-ui/components/inputs/maskedtextbox/

http://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/

**Comment by inikolova** [comment]
Related to: https://github.com/telerik/kendo-angular-inputs/issues/91

**Comment by inikolova** [comment]
Fixed:
http://www.telerik.com/kendo-angular-ui/components/inputs/maskedtextbox/

http://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/
