### ISSUE TITLE
Misaligned spinner icons in NumericTextBox

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#224]
![numeric](https://cloud.githubusercontent.com/assets/1118895/23125593/2dd9c14a-f77b-11e6-8d32-78cf04605044.png)

http://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/

**Comment by joneff** [comment]
See https://github.com/telerik/kendo-theme-default/issues/220#issuecomment-281053309

The demo site is using an older version of the theme. @inikolova has fixed the issue.
