### ISSUE TITLE
Grid Edit button's color almost identical with the selected row's background

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#234]
The Edit button does not stand out enough when a row is selected:

[http://plnkr.co/edit/CjXHwNeuWRVboWezW9IC?p=preview](http://plnkr.co/edit/CjXHwNeuWRVboWezW9IC?p=preview)

**Comment by yordanov** [comment]
After numerous iterations with different text and background colors, my personal belief is that we should keep the `$accent` color for `k-state-selected`, but make it lighter for Grid-like components. In addition text color need to be updated accordingly for readability. Changing the `primary` button styles in selected row in not an option as it is too specific and error-prone aproach. 

![grid-selection](https://cloud.githubusercontent.com/assets/1118895/23304726/ffe27972-faa3-11e6-9e45-0f2347fa148a.png)

See https://github.com/telerik/kendo-ux/commit/93ac935257bd39d0f2eb1cffe6223ddd53890231 for the actual opacity and colors used.
