### ISSUE TITLE
Clear button overlaps the selected ComboBox item

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-theme-default#261]
[https://www.screencast.com/t/XOEMXr58FDj](https://www.screencast.com/t/XOEMXr58FDj)
After selecting an item that is longer than the conbobox input size, its value overlaps the the clear button (after selection of an item, when the focus is on the combobox).

**Comment by inikolova** [comment]
Related to: https://github.com/telerik/kendo-angular-dropdowns/issues/214
