### ISSUE TITLE
Grid sorted column header use incorrect text color

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-theme-default#272]
Grid sorted column header should use selected-text color:
![sorted_header](https://cloud.githubusercontent.com/assets/16577622/23618428/f74dbe5a-0298-11e7-9e68-c6ff68defddf.png)

**Comment by inikolova** [comment]
We can leave this issue until a design for multiple sorted columns is available

CC @yordanov

**Comment by yordanov** [comment]
Grid sorting design added with https://github.com/telerik/kendo-ux/commit/7ef8e29e6c3a1c8582ed2f9cb3ff2efd36476c59

@lkarakoleva and I think that this is the most optimal, user and implementation friendly option.

**Comment by theOrlin** [comment]
This is already styled in accordance with the latest design.

- Design: https://github.com/telerik/kendo-ux/blob/master/themes/default/grid.psd
- Demo: http://demos.telerik.com/kendo-ui/grid/sorting
