### ISSUE TITLE
DatePicker / ComboBox styles

### ISSUE THREAD

**Issue by davshoward** [telerik/kendo-theme-default#31]
Does this contain the styles for the datepicker/combo box?

**Comment by ggkrustev** [comment]
This repo contains styles for our Kendo UI components for React/Angular2.

Styles can be found here:
- Calendar: https://github.com/telerik/kendo-theme-default/tree/master/styles/calendar
- ComboBox/DropDownList: https://github.com/telerik/kendo-theme-default/tree/master/styles/dropdowns

Date/Time pickers styling is not implemented yet.

**Comment by davshoward** [comment]
Okay thanks.

Is there a timeline for the date/time picker styles?

**Comment by ggkrustev** [comment]
There isn't, as the official roadmap is not out yet. Once the date/time pickers are planned (follow our official channels for the roadmap), then the styles will be available for the promised release date or earlier.

**Comment by gyoshev** [comment]
The official roadmap [has been published](http://www.telerik.com/kendo-angular-ui/roadmap/). This means the components are planned for the RC.0 release in January, and the styles will be included in the theme by then.

**Comment by davshoward** [comment]
Brilliant. Thank you :-)
