### ISSUE TITLE
MaskedTextBox input border is not visible

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-theme-default#331]
Compare how it looks on live (on the left side) and on staging (on right side) below:
[https://www.screencast.com/t/YeSkvw6Z](https://www.screencast.com/t/YeSkvw6Z)

**Comment by inikolova** [comment]
The issue is caused by this commit -> https://github.com/telerik/kendo-theme-default/commit/ea6998947a757293eda2c90d37c3c51a252adf0f

Which is related to https://github.com/telerik/kendo-angular-inputs/issues/91
