### ISSUE TITLE
Add styling for fieldset, textarea and validation

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-theme-default#332]
Add styling for fieldset, textarea and validation

Should be added in this demo, too: http://www.telerik.com/kendo-angular-ui/components/styling/theme-default/

**Comment by inikolova** [comment]
Styles for fieldset and textarea have been added

**Comment by gyoshev** [comment]
Closed via ab4b0ad34ddec893a15d44463b22dd4bd6215b19
