### ISSUE TITLE
Scrollview - wrong styling of prev/next arrows

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#342]
Current:
![scrollview](https://cloud.githubusercontent.com/assets/1118895/24237249/35398d76-0fae-11e7-889f-f6385d9c22a4.png)

Reference: [scrollview.psd](https://github.com/telerik/kendo-ux/blob/master/themes/default/scrollview.psd)

**Comment by inikolova** [comment]
This issue is caused by the following **Bootstrap rule**: 

`a:not([href]):not([tabindex]) {
    color: inherit;
    text-decoration: none;
}
`
which overrides the defined colors for **.k-scrollview-next, .k-scrollview-prev**
