### ISSUE TITLE
Calendar component doesn't center the navigation bar items

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-theme-default#353]
The issue can be seen in OSX, iOS and Android:
![screen shot 2017-03-27 at 10 22 24 am](https://cloud.githubusercontent.com/assets/495188/24344927/5f2a3e3e-12d6-11e7-8946-efd24dc3da82.png)

**Comment by gyoshev** [comment]
Issue is caused by the lack of a scrollbar in OSX. It needs more investigation, but the most robust solution may be to require JS to detect the scrollbar width.
