### ISSUE TITLE
Scheduler widget - Wrong timeslot borders' color

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-theme-default#376]
- Reproducible in IE and FF, not reproducible in Chrome and Edge
- URL: kendo-ui/scheduler/index 

![image](https://cloud.githubusercontent.com/assets/6614183/24754187/14372576-1ade-11e7-8ae3-32708bdc9858.png)

**Comment by joneff** [comment]
Fixed by https://github.com/telerik/kendo-theme-default/pull/558
