### ISSUE TITLE
Calendar issues.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-theme-default#390]
- [x] Text in Calendar's cell is not centered.
 **Actual**: https://www.screencast.com/t/odGL7fork

- [x] Background color of selected cell is not changed on hover and focus.
 **Design**: https://www.screencast.com/t/fobfKZxuCd)

- [ ] Current selected year/decade or century of outer view has wrong style:
 **Design**: https://www.screencast.com/t/lqi7mflYHrY
 **Actual**: https://www.screencast.com/t/tp2uLRXcaM

- [x] There is а black border between the head and body of calendar, which does not corerspond to the design.
 Actual:https://www.screencast.com/t/yWv3gQGyUb
 _Note: Border's color is correct in Chrome, but the shadow is missing._

- [x] There is a large padding in the decade view
https://www.screencast.com/t/K9Sway1603c

**Comment by theOrlin** [comment]
The Calendar design has been updated: https://github.com/telerik/kendo-ux/blob/master/themes/default/calendar-jquery.psd

**Comment by theOrlin** [comment]
The Calendar rendering does not provide for current year/decade/century. The only current date is "today" in Month view. The border of the year/decade/century is the focused state, and is correct.
