### ISSUE TITLE
Inputs issues.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-theme-default#392]
- [x] Invalid style of NumericTextBox is wrong. Arrorw keys should be colored in red.

 Design: https://www.screencast.com/t/q49KnecO
 Current: https://www.screencast.com/t/q49KnecO
- [x] Input's text is not centered in IE.
Actual: https://www.screencast.com/t/9wBei2Myu2

**Comment by inikolova** [comment]
The second issue has been already addressed -> https://github.com/telerik/kendo-theme-default/issues/370
