### ISSUE TITLE
Spreadsheet dialogs' issues

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-theme-default#415]
URL: kendo-ui/spreadsheet/validation 
- Wrong appearance of dialog buttons
  - Expected:
![image](https://cloud.githubusercontent.com/assets/6614183/25394509/e0f66a74-29e6-11e7-9fed-9042d1521500.png)
Note: The spreadsheet dialogs are implemented as kendo windows currently so they need to match the relevant design: https://github.com/telerik/kendo-ux/blob/master/themes/default/window-jquery.psd
  - Actual:
![image](https://cloud.githubusercontent.com/assets/6614183/25394522/e64e884e-29e6-11e7-8e0f-c21687e30a34.png)

- No icons for Orientation in Export to PDF
  - Expected (something similar to LESS skins?): 
![image](https://cloud.githubusercontent.com/assets/6614183/25394661/596c6328-29e7-11e7-82cc-62394431895e.png)
NOTE: icons bug logged - https://github.com/telerik/kendo-ui-core/issues/2697

  - Actual:
![image](https://cloud.githubusercontent.com/assets/6614183/25394623/406885fa-29e7-11e7-9b40-06488707c3de.png)

**Comment by Dimitar-Goshev** [comment]
- ~~[FIXED] Format dialog Cancel button is cut (dialog content on the right is not visible - in Date tab the vertical scrollbar is not visible):~~
![image](https://cloud.githubusercontent.com/assets/6614183/25476672/974eb846-2b43-11e7-8b82-bedc7535d875.png)

**Comment by Dimitar-Goshev** [comment]
- Wrong line color in Data Validation dialog (Default and Bootstrap):
![image](https://cloud.githubusercontent.com/assets/6614183/25477466/461a6936-2b46-11e7-91d3-d860fb8bad8b.png)

**Comment by joneff** [comment]
Related to https://github.com/telerik/kendo-theme-default/pull/233

**Comment by joneff** [comment]
The red header comes from the dialog component, where as in spreadsheet we use window component. As soon as we switch to using the former, the colors will match the design

**Comment by mparvanov** [comment]
- [x] Wrong line color in Data Validation dialog (Default and Bootstrap):
![image](https://user-images.githubusercontent.com/7202037/29453470-774020da-8412-11e7-9b93-6e820bf7ab4b.png)
