### ISSUE TITLE
The k-i-loading icon is not aligned horizontally in Autocomplete component

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-default#417]
### Bug report

The k-i-loading icon is not aligned horizontally in Autocomplete and Multiselect components.
![image](https://cloud.githubusercontent.com/assets/7202037/25431309/b2d79ef4-2a88-11e7-939d-b2714f4334a2.png)
![image](https://cloud.githubusercontent.com/assets/7202037/25431346/dae70196-2a88-11e7-809d-91006060f46b.png)

### Current behavior
The icon is not vertically aligned: 
[https://www.screencast.com/t/tzsoYhNa53Px](https://www.screencast.com/t/tzsoYhNa53Px)

### Expected/desired behavior
The icon is vertically aligned

**Comment by inikolova** [comment]
Can be observed in the Kendo UI Angular demos, too -> http://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/data-binding/
