### ISSUE TITLE
The group label in dropdowns popup is squashed

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-default#418]
### Bug report

The group label in Combobox, Dropdown and Autocomplete popup is squashed a bit:

![image](https://cloud.githubusercontent.com/assets/7202037/25430927/2c743c10-2a87-11e7-9418-7d29fe8816bc.png)

Reproducible for:

- combobox
- autocomplete
- dropdownlist

**Comment by NePheus** [comment]
Workaround for now:

```
.k-popup .k-list .k-item > .k-group:before {
    top: 0;
}
```
