### ISSUE TITLE
Map issues

### ISSUE THREAD

**Issue by boyandim** [telerik/kendo-theme-default#424]
- [ ] **1. The markers is barely visible in some cases.**

Please refer to the following screenshot: 
![2017-04-26_1948](https://cloud.githubusercontent.com/assets/3042944/25446380/0bcecd44-2aba-11e7-884a-a7774248c58a.png) 

Please check the [http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/map/angular](http://kendobuild-staging.openstack.progress.com/staging-kendo-ui/map/angular) demo.

**Comment by theOrlin** [comment]
There is no defined color for the map marker and this is the inherited body color. Will need assistance from a designer to decide on a default color.

@lkarakoleva @yordanov

**Comment by yordanov** [comment]
Let's use the `$accent` color as the default marker color.
