### ISSUE TITLE
Missing indicator for Spreadsheet range resizing

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-theme-default#428]
URL: kendo-ui/spreadsheet/validation
Select a range:

**Expected** (as in Default 1): Indicator in bottom right corner
![image](https://cloud.githubusercontent.com/assets/6614183/25478567/51aa5104-2b4a-11e7-8729-af7163ea2f54.png)

**NOTE:** When the indicator is hovered, the pointer should become a large black cross.

**Actual**:
![image](https://cloud.githubusercontent.com/assets/6614183/25478536/250abe4a-2b4a-11e7-85c1-d5d15c8b3e98.png)

**Comment by joneff** [comment]
Fixed by 2f1cd95ee6ee204234fe1fb17f7581f73750b53b
