### ISSUE TITLE
jQuery grid locked columns breaks display of remaining unlocked columns

### ISSUE THREAD

**Issue by sprell** [telerik/kendo-theme-default#472]
For projects needing to use both jQuery and Angular2 Kendo components, my understanding is that we should use the new @progress/kendo-theme-default for both instead of the jQuery specific themes. This theme is supposed to be compatible with both libraries (where the jQuery specific ones are not). However, when doing so, the jQuery grid will not display the data for unlocked columns correctly (or at all) when having one or more columns locked. This was working fine with @progress/kendo-theme-default version 2.28.1 but is now broken with version 2.32.3.

I have an example where I changed this jQuery grid demo...
http://demos.telerik.com/kendo-ui/grid/frozen-columns
...to use the new @progress/kendo-theme-default.

Here is the modified version...
http://dojo.telerik.com/aNUSa

All I did was replace the existing CSS with this...
http://www.telerik.com/kendo-angular-ui/npm/node_modules//@progress/kendo-theme-default/dist/all.css

**Comment by sprell** [comment]
More info: I looks like it was this change in v2.31.0 that broke it...
https://github.com/telerik/kendo-theme-default/pull/400
https://github.com/telerik/kendo-theme-default/commit/7aacef22

It works fine in v2.30.0 (the one just prior to that change).

**Comment by gyoshev** [comment]
Thanks for reporting this. As noted in the linked issue, this is [resolved in the latest Kendo UI for jQuery release](http://dojo.telerik.com/@gyoshev/EXoto) -- an immediate workaround is to use `display: block` or the `k-display-block` class on the grid.

We strive to prevent such problems and will be adding this to our test cases.
