### ISSUE TITLE
Incorrect alignment of items in Spreadsheet More formats dropdown

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-theme-default#475]
Number, Percent, Financial, etc. should be on the right.

![image](https://cloud.githubusercontent.com/assets/6614183/25665832/6b5afbd0-3027-11e7-81bb-61df997d6174.png)

**Comment by joneff** [comment]
Fixed by 	e66bf99

**Comment by joneff** [comment]
Fixed by 2ea64f4e6fb6c92b13dd00a594a560a87868001c
