### ISSUE TITLE
Progress bar is not shown.

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-theme-default#481]
This is the progress bar in Default skin:
![default](https://cloud.githubusercontent.com/assets/5861835/25710777/f3245722-30f5-11e7-86fd-586040d846e4.png)

And this is the progress bar in Default V2 skin:
![default2](https://cloud.githubusercontent.com/assets/5861835/25710785/f7f54554-30f5-11e7-804d-521b23af4177.png)

**Comment by theOrlin** [comment]
Also applies to https://github.com/telerik/kendo-theme-bootstrap
