### ISSUE TITLE
Angular TabStrip needs additional class

### ISSUE THREAD

**Issue by rusev** [telerik/kendo-theme-default#495]
Related to this issue - https://github.com/telerik/kendo-angular-layout/issues/114

We will need additional class for supporting `height` property of the Angular TabStrip. Suggested name `k-tabpstrip-flex`.

**Comment by gyoshev** [comment]
Turns out no additional class is needed, as the same styles are required for the jQuery TabStrip.

**Comment by gyoshev** [comment]
Test case: http://dojo.telerik.com/@gyoshev/EpIZe

**Comment by rusev** [comment]
It doesn't work in the Angular version - http://plnkr.co/edit/be7UTJjUBiSXAqJSoqP0?p=preview
