### ISSUE TITLE
latest npm build doesn't include scss folder

### ISSUE THREAD

**Issue by ncrawlins** [telerik/kendo-theme-default#509]
see title. breaks anyone using scss and customization. breaks your bootstrap theme as well.

**Comment by gyoshev** [comment]
I tried to reproduce the problem with 2.36.0 that was available at the time of writing, but the files are available. Also tried with the latest (2.37.0). It seems the issue is resolved -- please post more details if it persists.

**Comment by davidcasey** [comment]
I am experiencing this issue as well, no scss folder. I'm not sure why NPM versions (1.33.4) aren't matching GitHub (2.45.2).

$ npm install --save @telerik/kendo-theme-default

In package.json:
    "@telerik/kendo-theme-default": "^1.33.4",

Inside node_modules/@telerik/kendo-theme-default/
build/
dist/
docs/
styles/
.npmignore
package.json
README.md
webpack.config.js

**Comment by gyoshev** [comment]
@davidcasey this seems like a problem with the package name, as described in https://github.com/telerik/kendo-angular/issues/195. Also, make sure that you are using the public NPM registry, as we have [retired the private NPM registry](https://github.com/telerik/kendo-angular/issues/712).
