### ISSUE TITLE
Having issues on using scss

### ISSUE THREAD

**Issue by NTPLThavarajan** [telerik/kendo-theme-default#514]
I am using the [Angular advanced Sedd](https://github.com/NathanWalker/angular-seed-advanced)
**if I include the All SCSS then the following error appears**
`Error: EMFILE: too many open files, open`
if I include the CSS there is no problem,
**Note I have already included the bootstrap scss in my project**
At present we have 30 components, it may be grown further
Any ideas? why this is happening, any solution to prevent this issue,
My system details are as follows
OS: Windows_NT 6.1.7601
Node: v6.10.0
Npm: v3.10.10

**Comment by gyoshev** [comment]
Looking at other GitHub issues, this seems to be a problem in the build configuration of the project. [See this thread](https://github.com/kevlened/copy-webpack-plugin/issues/59) for suggestions on how to resolve this.

**Comment by NTPLThavarajan** [comment]
Thanks @gyoshev 
But in seed they didn't use any webpack plugins, any way I will give a look into that link
