### ISSUE TITLE
Spreadsheet - Export dialog is not properly styled in SASS themes

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-theme-default#523]
For Default v2 and Bootstrap v4, in "Export" dialog, document format PDF, are missing:
1. separation between the main dialog inputs (file name, save as type) and the PDF options;
2. missing document orientation preview icon;
3. missing font icons in the orientation buttons (this is valid for LESS themes as well)

[Design Reference](https://github.com/telerik/kendo-ux/blob/master/themes/default/component-dialogs.psd):
![2](https://cloud.githubusercontent.com/assets/16577622/26627671/e7cb8b3e-4603-11e7-8cea-3090f3e4f330.png)

Implementation:
![1](https://cloud.githubusercontent.com/assets/16577622/26627641/d07bacc0-4603-11e7-8288-1c819a95718c.png)

**Comment by joneff** [comment]
1) Done; 3) done

2) will require extra work, so i've logged a separate item for that

**Comment by mparvanov** [comment]
There are the following inconsistencies in SASS:
- [x] ~~Checkboxes are not styled according to the design~~
- [x] Export icon size and position is not according to the design
![image](https://user-images.githubusercontent.com/7202037/29407766-3c780be4-834e-11e7-98bb-733c98c540c5.png)

- [x] ~~Missing border in File Name input for default themes:~~
![image](https://user-images.githubusercontent.com/7202037/29407851-99978b74-834e-11e7-871c-e0906847db96.png)

**Comment by joneff** [comment]
Checkboxes are targeted with https://github.com/telerik/kendo-theme-default/pull/693.

Note: this is the correct appearance for the checkboxes. With this pull request I've improved the hover and focus state

**Comment by joneff** [comment]
The cutout border happens in the demos as well i.e. it's not a new issue

**Comment by joneff** [comment]
Export preview icon target with #694
