### ISSUE TITLE
Grid locked cells border breaks after scroll in RTL

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-theme-default#533]
Can be observed in this example: http://plnkr.co/edit/JYrYJolbEc71bAF9xQqK?p=preview

Note: this problem occurs only in Chrome

**Comment by gyoshev** [comment]
Appears fixed with latest versions, [StackBlitz demo](https://stackblitz.com/edit/angular-ck4wds?file=app/app.component.ts).
