### ISSUE TITLE
Default input styles don't appear to have enough contrast on borders

### ISSUE THREAD

**Issue by 06b** [telerik/kendo-theme-default#562]
Received feedback that inputs such as text boxes don't appear to have much contrast and can be hard to see. 

Was able to confirm by comparing the Default Less theme to the Default v2 Sass Theme on the MaskedTextBox demo - http://demos.telerik.com/kendo-ui/maskedtextbox/index

![kendobordercontrast](https://user-images.githubusercontent.com/1302542/27494392-aeae9ea2-581b-11e7-8c9b-678d6e3cf509.gif)

**Comment by gyoshev** [comment]
Thank you for the suggestion. As the color visibility depends on the specific application and changing it will affect all customers, we are reluctant to change it unless there is a significant feedback in that direction. In your application, you can change the color by setting the `$base-border` variable, in the way [documented in the styling help topic](http://www.telerik.com/kendo-angular-ui/components/styling/#toc-custom-themes).
