### ISSUE TITLE
Grid filter row not rendered correctly in IE when Grid has height and wrapped headers

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#569]
When the Grid headers are wrapped, and the Grid height option is set, the filter row is not rendered correctly in IE:
[http://plnkr.co/edit/nCBRMkEcLE9ia9GeWet9?p=preview](http://plnkr.co/edit/nCBRMkEcLE9ia9GeWet9?p=preview)

The following CSS resolves the issue:

    .k-grid-header {
      flex: 0 0 auto;
    }

[http://plnkr.co/edit/8iuDVpcEmBbuue2mxBN1?p=preview](http://plnkr.co/edit/8iuDVpcEmBbuue2mxBN1?p=preview)

**Comment by siyka-marinova** [comment]
Fixed in `@progress/kendo-theme-default v2.38.1`
