### ISSUE TITLE
Document forms styles

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#57]
We should have the styles documented in a way similar to http://docs.telerik.com/kendo-ui/styles-and-layout/appearance-styling#customize-checkboxes-and-radio-buttons

- [x] Checkbox
- [x] RadioButton
- [x] TextBox
- [ ] Validation
- [x] FieldSet
- [x] Textarea

**Comment by tsvetomir** [comment]
@gyoshev I assume we should take over the docs for the K2 site

**Comment by gyoshev** [comment]
Topic is [available on the site](http://www.telerik.com/kendo-angular-ui/components/forms/), opening a new issue regarding validation in the site repo.
