### ISSUE TITLE
Extending dialog /window to include variables for customization 

### ISSUE THREAD

**Issue by IanMuirhead** [telerik/kendo-theme-default#571]
I'm trying to add variables to the `dialog` component and properly import it into the theme.

From what I can tell the theme isn't being included properly and I am unsure how to troubleshoot the issue.

I have a forked repository with a branch with the changes I've made so far. 

https://github.com/copperleaftech/kendo-theme-default/tree/feat/dialog-variables

An example of what is confusing me. You can see that the classes that are being added are `k-window-title k-dialog-title` but in the generated CSS there is no declarations for `k-dialog-title`.

![image](https://user-images.githubusercontent.com/884395/27666091-462ff22c-5c26-11e7-8294-79691b0fc595.png)

If you look at the scss files - I am perplexed as to why it isn't being generated. I have included a snippet of the declaration I've added to my fork below.

```   
 .k-dialog-title {
        color: $dialog-title-font-color;
        margin: 0;
        font-size: $dialog-title-font-size;
        line-height: 1;
        text-overflow: ellipsis;
        overflow: hidden;
        cursor: default;
        flex: 1;
    }
```

I think I'm missing something really obvious here - any idea if you can nudge me in the right direction?

**Comment by gyoshev** [comment]
By design, the dialog inherits styles from the window component, which is [available in Kendo UI for jQuery](http://demos.telerik.com/kendo-ui/window/index). The dialog component extends these styles to add the action buttons functionality. Most likely the introduced variables need to work with the window styles.

**Comment by IanMuirhead** [comment]
@gyoshev Understood.  

Looks like I had something irked on my local not pulling in my virtual folders properly. d'oh.

I'll fix up my implementation and submit a pull request to see if you're interested in including it in the main theme.
