### ISSUE TITLE
Theme entry points

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-theme-default#58]
After some months of usage, it seems that we have found the required entry points for theme usage:

1. include the whole theme CSS (via `dist/all.css`)
2. include the whole theme via source (via `src/theme.scss`)
3. create a custom theme build via source (by including multiple files, e.g. `src/grid/main.scss` and `src/treeview/main.scss`)

However, the entries leak file names that provide no useful information in customer applications:

     // there is one distribution file, no need for "all"
     @import "~@progress/kendo-theme-default/dist/all";

     // second "theme" is redundant
     @import "~@progress/kendo-theme-default/src/theme";

     // "main" provides no information
     @import "~@progress/kendo-theme-default/src/grid/main";

Thus, I would like to suggest the following file changes:

1. `/dist/all.css -> /dist.css`
2. `/src/theme.scss -> /src.scss`
3. `/src/grid/main.scss -> /src/grid.scss`

The above will expose a very consistent naming for the entry points:

1. `"~@progress/kendo-theme-default/dist";` imports the CSS of the complete theme
2. `"~@progress/kendo-theme-default/src";` imports the source of the complete
3. `"~@progress/kendo-theme-default/src/grid";` imports the source of the grid

This makes both customer scenarios and derived themes very specific about what is used -- distribution files or source. It also reduces boilerplate.

@joneff @inikolova @theOrlin @melhaer -- comments or questions are welcome. Would love to clear this up before merging v2, to prevent breaking changes due to naming.

**Comment by tsvetomir** [comment]
Sounds like a great improvement. I'd make the format of the entry point more explicit
1. "~@progress/kendo-theme-default/**css**"; imports the CSS of the complete theme
2. "~@progress/kendo-theme-default/**scss**"; imports the source of the complete
3. "~@progress/kendo-theme-default/**scss**/grid"; imports the source of the grid

**Comment by gyoshev** [comment]
I like the explicit naming, since it becomes clear what is being imported. However it introduces a bit of awkward naming when used to reference the CSS file directly:

      "styles": [
          "../node_modules/@progress/kendo-theme-default/css.css"
      ]

I don't like that very much, and it is the more common case for referring to the CSS file... Bootstrap have taken a mixed approach, [using a `dist` and `scss` folder](https://github.com/twbs/bootstrap), which seems a solution for this. What do you think?

**Comment by tsvetomir** [comment]
Agreed, **css.css** doesn't sound very well. I like the Bootstrap approach, **dist** and **scss** folders sound better.

**Comment by joneff** [comment]
Speaking of Bootstrap, they don't really mind repeating the bootstrap name in files. With that in mind, i am still in favour of keeping the `theme` names e.g.

* `~@progress/kendo-theme-default/dist/theme.css`
* `~@progress/kendo-theme-default/src/theme.scss` or alternatively
* `~@progress/kendo-theme-default/scss/theme.scss`

I am somewhat against having files that are outside the dist / src folders and emulate magical inclusion.

Within the source folder, be it src or scss, i am OK with having `grid.scss` that includes whatever is needed for the grid styles. In a way, this will simplify development as there will be no partials and completes (minus the global variables file) residing in the same folder.

**Comment by joneff** [comment]
Come to think of it, having `/src/component-name.scss` files, might actually be a good idea. It could be, if such thing existed in css terms, our public facing API. In terms:

```scss
// i want to use the entire theme as compiled
@import "~@progress/kendo-theme-default/dist/theme.css";

// i want to use the entire theme, but customize it
@import "~@progress/kendo-theme-default/src/theme"; // or theme.scss

// I want to use specific components
@import "~@progress/kendo-theme-default/src/grid"; // or grid.scss
@import "~@progress/kendo-theme-default/src/combobox"; // or combobox.scss

// (in the context of theme development) I want to use just the layout of the editor
@import "~@progress/kendo-theme-default/src/editor/layout"; // or _layout.scss
```

**Comment by tsvetomir** [comment]
To me `src` sounds like something that I shouldn't be using directly. Replacing it with `scss` clears up any confusion.

**Comment by gyoshev** [comment]
It seems that we are all on the same page about the following renames:

- `src/ -> scss/`
- `scss/grid/main.scss -> scss/grid.scss` 

I am strongly against keeping the name `scss/theme.scss` as it is -- it does not describe its contents, and is in clash with the `scss/grid/_theme.scss` file which does not hold the complete grid theme.
I am OK with renaming it to `scss/all.scss` and not having "magical" files outside the scss and dist folders. Bonus points for not breaking the current `dist/all.css` naming.

**Comment by joneff** [comment]
`src/ -> scss/` 👍 

The discussion is getting long-ish. Let's go with `all` for now. If we need to, we can always have v3
