### ISSUE TITLE
Titlebar font don't increase

### ISSUE THREAD

**Issue by clarinetluis** [telerik/kendo-theme-default#588]
If you increase the size of the typography, the text of the windows title of the native applications is not increased

**Comment by joneff** [comment]
I am not quite sure I understand what the issue is. Could you elaborate a bit more?

**Comment by clarinetluis** [comment]
a picture is worth a thousand words
![pantallazo](https://user-images.githubusercontent.com/29948023/27983285-32b628ca-63b9-11e7-8407-2c168045c8c6.jpg)

**Comment by gyoshev** [comment]
@clarinetluis do you need the window/dialog title font to be fixed when the page font changes? The dialog window on the image shows a OS dialog and we could not understand the problem. Providing a Plunkr snippet that illustrates the problem in the context of the theme will eliminate the confusion.

**Comment by clarinetluis** [comment]
**@gyoshev @joneff** #font-size don't adjust in some aplications titlebar

  I adjust the size of the font to ubuntu mediun 13 and the font size of some aplications does not increase
![bug](https://user-images.githubusercontent.com/29948023/28395656-ce39558e-6cf5-11e7-8ac8-1b697ce28511.jpeg)

**Comment by gyoshev** [comment]
@clarinetluis how does this affect the Kendo UI components? This repository is for issues in the Kendo UI default theme, which can be seen on [this demo page](http://www.telerik.com/kendo-angular-ui/components/styling/theme-default/).
