### ISSUE TITLE
Grid, grouping does not work

### ISSUE THREAD

**Issue by DominikJaniec** [telerik/kendo-theme-default#600]
# Bug: Groups reorder does not work

Using this Dojo: http://dojo.telerik.com/OXaVa/6
You could see how grouping does not work (or sometimes works) like on attached GIF.
![not_so_groupable](https://user-images.githubusercontent.com/3832797/28022053-3be78fd8-658a-11e7-8a5d-c8ce50a9c45a.gif)
GIF is from Chrome, but this effect is also in Firefox or IE.

In fact problem is with impossibility (or lack of luck) to select certain positions at Groups' header.
I'm using SASS version of yours theme, but at Dojo is same behavior like in my case.

----
Also I would like to point that there is no way to move column's ordinary header to the last position. You have to drop it at next-to-last position and then drag the last one to the left. Additionally "drop indicators" for columns reorder are at bottom of the page, instead of between target Headers.
But I think you are aware of it: https://github.com/telerik/kendo-ui-core/issues/3250

**Comment by gyoshev** [comment]
Thank you for reporting this. It appears the issue is caused by the theme, as the problem does not occur with other themes. Requires further investigation on why it happens.

**Comment by joneff** [comment]
@DominikJaniec @gyoshev the issue is caused by missing styles for grid column reordering. When hovering adjacent columns, the reorder indicators appear below the grid and take ever so slightly more space (about 1em or 1rem), hence the scrolling.

That should be a straightforward fix.

**Comment by joneff** [comment]
Needs https://github.com/telerik/kendo-theme-default/pull/696

**Comment by matanasov** [comment]
@joneff 
The main issue is still not resolved - drag a column to the grouping toolbar and drop it **between other columns**. Note that drag-drop **in the first/last** position seems to work as expected

**Comment by matanasov** [comment]
@theOrlin 
The issue is still valid:
1. Group by `Order Date`
2. Add `Ship Country` grouping **after** `Order Date`
3. Add `Ship City` grouping **after** `Ship Country`
4. Add `Ship Name` grouping **as a middle group** - it is not added!
