### ISSUE TITLE
MultiSelect tag close icon is misaligned

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-default#61]
Using 2.0.1 version. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/4188451/21602850/f5ef03e4-d1a0-11e6-91ea-bd7a9a77dbe5.png)

**Comment by inikolova** [comment]
This is caused by the example uses old CDN-s. Removing them seems to fix the problem

**Comment by KirilNN** [comment]
that was so stupid! apologies
