### ISSUE TITLE
MutliSelect focused state not visible enough

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-default#62]
Currently the focused state on tags and list items is not visible enough, maybe we can harden it a little bit. On the screenshot below the focused item is Cricket
![image](https://cloud.githubusercontent.com/assets/4188451/21638037/339ca79c-d272-11e6-827d-2ac46a17c8d2.png)

cc @yordanov

**Comment by yordanov** [comment]
Here is how the states should look like:

![multiselect](https://cloud.githubusercontent.com/assets/1118895/21641008/9f04e2b0-d281-11e6-93c6-bb315ce2c77b.png)

**Comment by inikolova** [comment]
Done: e9a39afa6a1c9eca1570ded
