### ISSUE TITLE
Grid's cells of new item has wrong height.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-theme-default#636]
1.Navigate to:
http://dojo.telerik.com/IXiCa
2.Add new item
3.Blur outside the new item

Result: Cells of new item have different height compare to the existing items.
https://www.screencast.com/t/w4tOL4QN

Valid for default and bootstrap themes.

**Comment by theOrlin** [comment]
This is the expected behavior of rows in the Grid empty of content. The grid rows need content to have proper height.
This can also be observed in the old LESS themes.
