### ISSUE TITLE
RTL styles for the slider 

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-theme-default#637]
Since the k-rtl class is not used in the angular components for some reason we need additional selectors for the dir attribute. 

An issue caused by the missing styles can be observed in the inputs RTL demo - reversed buttons.
http://www.telerik.com/kendo-angular-ui/components/inputs/rtl/

**Comment by siyka-marinova** [comment]
Fixed in `@progress/kendo-theme-default@2.39.0`
