### ISSUE TITLE
Grid clear filter button is missing and causes flickering when filter value is entered.

### ISSUE THREAD

**Issue by matanasov** [telerik/kendo-theme-default#650]
This is valid for all browsers for **both Default and Bootstrap** themes.

Before value is entered:
![before](https://user-images.githubusercontent.com/5861835/28678283-aa238a4e-72f8-11e7-9d97-c87f719853d9.png)

After value is entered:
![after](https://user-images.githubusercontent.com/5861835/28678292-b1828268-72f8-11e7-8833-7954c8ca8ae1.png)

**Comment by theOrlin** [comment]
The Numerictextbox should resize properly now.
