### ISSUE TITLE
Filter icons in Grid are missing vertical paddings

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#668]
In the latest version the Grid filter icons are missing vertical paddings. Observable in the online demos:

[http://www.telerik.com/kendo-angular-ui/components/grid/filtering/](http://www.telerik.com/kendo-angular-ui/components/grid/filtering/)

**Comment by tsvetomir** [comment]
Please let me know as soon as you get the official release out. I'll re-upload the site with the fixed theme.
