### ISSUE TITLE
Column content overflows grid boundaries when virtual scroll enabled using new default theme.(v2.39.1)

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-theme-default#669]
The issue can be observed in the following Dojo with the included styles:

http://dojo.telerik.com/OWOmu/2

The issue can be related to the recent changes of the Grid rendering from v2.39.0

**Comment by gyoshev** [comment]
Thanks for reporting this. By the way, the theme is published on the official NPM registry, so you can refer it through unpkg, like this:

    <link rel="stylesheet" href="https://unpkg.com/@progress/kendo-theme-default@2.39.0/dist/all.css" />

The latest development version can be referenced through the dist-tag:

    <link rel="stylesheet" href="https://unpkg.com/@progress/kendo-theme-default@dev/dist/all.css" />

It seems the problem [still appears in `2.40.1`](http://dojo.telerik.com/@gyoshev/iJUKE).

**Comment by simonssspirit** [comment]
The issue seems to be fixed in the latest version, please confirm?

**Comment by gyoshev** [comment]
It seems so. Might be related to the latest fixes in the grid. Closing.
