### ISSUE TITLE
Slider and Switch focused state is not styled

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-theme-default#671]
I've added `k-state-focused` classes to the Slider and Switch components, but the styles are not there yet.

Can be seen on [staging](http://kendobuild/kendo-angular-ui-develop/components/inputs/).

**Comment by tsvetomir** [comment]
The Slider handles don't seem to have a shadow when focused.

**Comment by siyka-marinova** [comment]
Fix is available in `@progress/kendo-theme-default@2.40.0`
