### ISSUE TITLE
Forms layout for Angular 2 Default theme

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#69]
We need to provide and document ways (be it styles, markup, grid layout...) to easily style forms with the Angular components.

The most common use case, we need this for, is for Editing in complex components like Grid:

![grid-forms](https://cloud.githubusercontent.com/assets/1118895/21686216/45e94364-d36d-11e6-929e-e4edabc6bd39.png)

Here is how forms could look like:

![forms](https://cloud.githubusercontent.com/assets/1118895/21098275/1fa2e642-c071-11e6-97c9-a7778a5c58d0.png)

**Comment by gyoshev** [comment]
I believe that we shouldn't re-invent a grid layout. I'm in favor for including bootstrap in the demos and using it in the templates. This will both solve the issue in the demos, and allow customers to use a different grid layout (e.g. foundation), if required. Plus, no bloat of having two layout systems.

@petyosi does that sound reasonable?

**Comment by petyosi** [comment]
I am ok with using bootstrap for the layout/columns. We should still have styling for the form elements and the validation, though.

**Comment by gyoshev** [comment]
The popup editor layout is [pushed in the **grid-editing** branch](https://github.com/telerik/kendo-angular-grid/commit/d11d87e889fce60794337ffac5a580410cf49759). Invalid states come from the theme.
