### ISSUE TITLE
Checkbox and radiobutton appearance

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-theme-default#695]
Currently, we have two conflicting sets of appearance for checkboxes / radiobuttons:

* in forms.psd, we have red background with white checkmark / dot
* in components-dialog.psd, we have white background with red checkmark / dot

Which one is it?

**Comment by lkarakoleva** [comment]
Let's keep the forms.psd design - red background and white checkmark/dot. I will update components-dialog.psd

**Comment by lkarakoleva** [comment]
Updated design: https://github.com/telerik/kendo-ux/blob/master/themes/default/component-dialogs.psd

**Comment by joneff** [comment]
Thanks
