### ISSUE TITLE
Buttons are misaligned in Grid editor templates

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#701]
Buttons and inputs in Grid editor templates are vertically misaligned:

[http://plnkr.co/edit/DqjLGNLmWfZe5z8PFkDG?p=preview](http://plnkr.co/edit/DqjLGNLmWfZe5z8PFkDG?p=preview)

Suggested workaround:

    .k-grid-edit-row>td>.k-button {
        margin-top: calc((1.4285714286em - (10px + 1.4285714286em)) / 2);
        margin-bottom: calc((1.4285714286em - (10px + 1.4285714286em)) / 2);
        vertical-align: top;
      }

**Comment by siyka-marinova** [comment]
Fixed in `@progress/kendo-theme-default@2.41.0`
