### ISSUE TITLE
No data template not positioned properly in IE

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#704]
The DropDowns components No Data template is not vertically centered in IE like it is in other browsers. Reproducible in the online demos:

[http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/templates/#toc-no-data-template](http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/templates/#toc-no-data-template)

Related to the following IE bug:

[https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview#tabs](https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview#tabs)

Workarounds:

    .k-popup { 
  	  display: flex;
  	}
or

    .k-nodata{ 
  	  height: 138px;
  	}

**Comment by siyka-marinova** [comment]
Fixed in `@progress/kendo-theme-default@2.41.1-dev.201709051522`

**Comment by siyka-marinova** [comment]
Released in `@progress/kendo-theme-default@2.41.1`
