### ISSUE TITLE
Wrong height on the icons only buttongroup

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-theme-default#705]
Icons only buttongroup should have the same height as the other buttongroup.

**Comment by siyka-marinova** [comment]
Fix is available in the dev. version of the kendo-theme-default package: `@progress/kendo-theme-default@2.41.0-dev.201709041059`

**Comment by siyka-marinova** [comment]
Released in `@progress/kendo-theme-default@2.41.0`
