### ISSUE TITLE
Grid has wrong width in IE.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-theme-default#724]
If some of Grid's columns has no width set, Grid's width is wrong in IE.
Valid for the both SASS themes.
Result: https://www.screencast.com/t/6VRkH2exa7

Demo:
pdf-export/index

Version - latest version of the scripts(internal)

**Comment by theOrlin** [comment]
This is due to IE problem with flexbox inside table. Adjusted the demo styles to remove the table rendering.

**Comment by MilenaCh** [comment]
MVC demo should be fixed also
