### ISSUE TITLE
Grid text filter input has wrong width in FireFox

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#730]
The text filter input is wider than it should be, causing the adjacent filter icons to not be displayed properly. Observable in FireFox only:

[http://plnkr.co/edit/wUnvHPyMRG1mHClOfBMQ?p=preview](http://plnkr.co/edit/wUnvHPyMRG1mHClOfBMQ?p=preview)

Suggested workaround:

    .k-filtercell .k-filtercell-wrapper > .k-textbox {
        width: 0;
        flex: 1 1 auto;
      }

[http://plnkr.co/edit/b5aToJpAdqhuNd0sWmkw?p=preview](http://plnkr.co/edit/b5aToJpAdqhuNd0sWmkw?p=preview)

**Comment by gyoshev** [comment]
Appears to be fixed by https://github.com/telerik/kendo-theme-default/commit/bda95b71b2a3279d771cfbc954cfe71af4ff897e and https://github.com/telerik/kendo-theme-default/commit/2067a93121603e4cf9797cf8feb96cb3dcb26e25
