### ISSUE TITLE
Button: Wrong .k-state-active (toggled style) for default button

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#732]
### [Reproduction](http://plnkr.co/edit/IL5LdTImdNKcl6zgLkER?p=preview)

Current toggled state:
<img width="73" alt="screen shot 2017-09-21 at 15 24 55" src="https://user-images.githubusercontent.com/1118895/30695552-2d41f168-9ee1-11e7-9158-cca37c5c4535.png">

Should be:
<img width="71" alt="screen shot 2017-09-21 at 15 25 25" src="https://user-images.githubusercontent.com/1118895/30695561-341cca8a-9ee1-11e7-8950-84110a744e8f.png">

For a detailed reference see the [buttons.psd](https://github.com/telerik/kendo-ux/blob/master/themes/default/buttons.psd).

**Comment by joneff** [comment]
After some design iterations, we have confirmed that the current behaviour is indeed the correct one
