### ISSUE TITLE
Grid resizing is not consistent to LESS themes behavior.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-theme-default#745]
1. Navigate to grid/column-resizing(use latest version of the themes)
2. Descrease the width of all columns

Result:
The width of some columns will be automatically increased.

Expected:
If decrease the columns width,an empty space in grid should left.(see less themes behavior)

Video:
https://www.screencast.com/t/dGWcsZD0Bu0

**Comment by theOrlin** [comment]
Should be fixed by https://github.com/telerik/kendo-theme-default/commit/b1485c15c97829314e37d3d9ea36a780819e1abf

**Comment by MilenaCh** [comment]
Resize handler disappears in IE:
1. Navigate to grid/column-resizing demo
2. Resize the first column to the min possible width
3. Try to resize the second column

Video:
https://www.screencast.com/t/tjCtDjPsP7oD

Note: The Header text from the first column overlaps the second column's header:
https://www.screencast.com/t/O1SfyhnCW3
