### ISSUE TITLE
 ColumnMenu icon is not aligned to the header text.

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-theme-default#746]
Problem:
https://www.screencast.com/t/Zde8UBUgKg

The issue could be observed in all SASS themes.(note, it's internal issue and could not be replicated with the official version)

**Comment by theOrlin** [comment]
Should be fixed by https://github.com/telerik/kendo-theme-default/commit/bbb4dc78229d8f07034ef3d355d6b42aa9c26538
