### ISSUE TITLE
Outline Button does not inherit color properties from its parent element  

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#760]
Default buttons and buttongroups with `[look]="'outline'"` should inherit color properties (e.g. `background-color`, `color`, `border-color` etc.) from their parent element. 

Reproduction Button - http://plnkr.co/edit/Go7PgyUdw9qIjQqbyx4r?p=preview

Reproduction ButtonGroup - http://plnkr.co/edit/O2BynTNu16IUsnQIJKKI?p=preview

Part of https://github.com/telerik/kendo-angular-buttons/pull/201

**Comment by joneff** [comment]
Fixed by https://github.com/telerik/kendo-themes/commit/c135b0654a17106ba3ec9855db2c811930f4d2e7

**Comment by mparvanov** [comment]
An explicit color instead of inherit is applied to k-outline class:
http://take.ms/VM41r
