### ISSUE TITLE
Plunker with Autocomplete breaks IE 11 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-theme-default#762]
Running a plunker with Autocomplete causes IE 11 to crash.

In order to reproduce, check the following sample plunker:

[http://plnkr.co/edit/Vu7re0ERLTKVlWZQBYD0?p=preview](http://plnkr.co/edit/Vu7re0ERLTKVlWZQBYD0?p=preview)

A possible workaround is to add the following style:
.k-autocomplete  { display: inline-block; }

**Comment by gyoshev** [comment]
This appears to be a bug specifically with the configuration of IE11 and plunker. Since the problem is only visible in plunker, and not simply in IE11 nor on the site, the provided workaround should be enough.
