### ISSUE TITLE
Toggled Button in Bare ButtonGroup does not inherit color properties

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-theme-default#763]
Reproduction:
http://plnkr.co/edit/bItvFdqeOs8KXWOqIpmc?p=preview

Part of https://github.com/telerik/kendo-angular-buttons/pull/201

**Comment by joneff** [comment]
Appears to be fixed. Check https://www.telerik.com/kendo-angular-ui/components/buttons/buttongroup/styling/

**Comment by joneff** [comment]
After several revisions, this items can be considered fixed.

You can check the preview

![](https://raw.githubusercontent.com/telerik/kendo-themes/develop/tests/visual/output/default/buttongroup.png)

https://raw.githubusercontent.com/telerik/kendo-themes/develop/tests/visual/output/default/buttongroup.png
