### ISSUE TITLE
Progressbar animation is applying value to end of the bar 

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-default#764]
After a certain point or percentage, it always moves to 100 % filled visually then back down to the point of value. The issue could be observed in the following dojo sample:

http://dojo.telerik.com/iKiDo

**Comment by magdalenaan** [comment]
The following CSS can be used for a workaround:
`.k-progressbar>.k-state-selected {
      position: absolute;
    }`

**Comment by magdalenaan** [comment]
Reported also in ticket ID 1136260
