### ISSUE TITLE
Increase z-index of the .k-header.k-drag-clue element

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#766]
Currently the clue element that appears while dragging the title of of a Grid column that will be used for grouping becomes invisible if there is something with z-index 1 on a page, e.g. mat-sidenav-container (z-index 1 by default) from Google Material Design.

[http://plnkr.co/edit/4lzjD42TRPgPk6Y5AhLd?p=preview](http://plnkr.co/edit/4lzjD42TRPgPk6Y5AhLd?p=preview)

Comment out the custom CSS suggested as a workaround to observe the issue.

It would be nice to increase the default z-index of the discussed element so that it appears above other elements and remains visible regardless of the z-index of the Grid container.

**Comment by PreslavKozovski** [comment]
I am closing this issue because, at this stage, the jQuery, Angular, and React Grids are assigning `z-index: 20000;` via JavaScript to the drag clues.
