### ISSUE TITLE
DropDownList not rendered correctly in IE if there is filter

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-theme-default#793]
### Bug report

DropDownList is not rendered correctly if there is a filter. Issue appear only in IE, only with SASS themes.
The items of the DropDownList are exceeding the height of the DropDownList container.

### Reproduction of the problem

1) Go to this [Dojo](http://dojo.telerik.com/ofEPIsAy) using IE. 
2) Select a SASS Theme.
3) Expand the DropDownList.

### Expected/desired behavior
All items of the DropdownList should be rendered inside the DropDownList container.

Workaround:
[http://dojo.telerik.com/Iqukav/5](http://dojo.telerik.com/Iqukav/5)

Reported in ticket ID 1141181

**Comment by Dimitar-Goshev** [comment]
Not reproducible with R3 2018 (2018.3.911)
