### ISSUE TITLE
Icons are displaced in button with direction RTL

### ISSUE THREAD

**Issue by mparvanov** [telerik/kendo-theme-default#818]
The issue is observed in the following sample: http://dojo.telerik.com/UzorO/2

Expected: The icons in RTL are positioned similar to the LTR
Actual: The icon overlaps the text in RTL mode: 

![image](https://user-images.githubusercontent.com/7202037/33712397-f15cbfe2-db4f-11e7-86ff-0c3e76608f6f.png)

**Comment by gyoshev** [comment]
When using RTL styles, either place the button in a `class="k-rtl"` container, or set `dir="rtl"` on the button itself. The first approach is documented for Kendo UI for jQuery, and the latter is how the Kendo UI for Angular button is rendered. The theme supports both approaches, and linking the `kendo.rtl.css` file is not necessary. Here is a [functional plunker](http://dojo.telerik.com/iDeSOpEx).
