### ISSUE TITLE
Grid Filter menu not wide enough in IE

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-theme-default#845]
The Grid Filter menu popup has different width in IE than in Chrome for numeric and date types (when there are DatePickers and NumericTextBoxes inside):

Chrome:

![image](https://user-images.githubusercontent.com/7533599/34599606-ea3064d6-f1fb-11e7-828e-c8bbf55f64c2.png)

IE:

![image](https://user-images.githubusercontent.com/7533599/34599613-fa5e0f66-f1fb-11e7-9529-4947456e8142.png)

**Comment by gyoshev** [comment]
A workaround that can be used immediately is to add a `min-width` to the grid filter popup with the following style:

```css
.k-grid-filter-popup {
    min-width: 200px;
}
```

Here is [a plunker](https://plnkr.co/edit/0Z7uDqemIiiaFni2zXzC?p=preview) showing that approach.

The fix in the theme will follow soon.

**Comment by svetq** [comment]
When using a different/longer text for the "Filter" and "Clear" buttons, the issue in IE persists. Also, the padding of the buttons is not proper in Chrome. A workaround that could be used is to apply the following styles:

>>> .k-filter-menu {
         min-width: 240px;
}
>>> .k-filter-menu>div>div>.k-button {
        width: auto
      }

Check the following sample plunker demonstrating the workaround:

[https://plnkr.co/edit/CiP45F2nyGVaAUy0xJy4?p=preview](https://plnkr.co/edit/CiP45F2nyGVaAUy0xJy4?p=preview)
