### ISSUE TITLE
DateTimePicker: Increase hit area for icons

### ISSUE THREAD

**Issue by 06b** [telerik/kendo-theme-default#857]
**Demo** - https://demos.telerik.com/kendo-ui/datetimepicker/index

Currently the DateTimePicker hit area is set to just the icon which requires some precision to hit since it's a 16px by 16px.

![capture20180117180254810](https://user-images.githubusercontent.com/1302542/35106316-ebd872de-fc3b-11e7-8e77-768df78d1488.png)

The small workaround below adjusts the hit area as follows:

![capture20180117180313940](https://user-images.githubusercontent.com/1302542/35106376-0dccf6e4-fc3c-11e7-8930-3fa24e01d729.png)

**Workaround:**
```
.k-datetimepicker .k-link
{
    display: flex;
    flex-direction: column;
}

.k-datetimepicker .k-link .k-icon
{
    display: flex;
    flex-grow: 1;
    align-items: center;
    justify-content: center;
    width: 100%;
}
```

**Comment by joneff** [comment]
Issue is related to javascript, not the theme in particular. Please follow the related kendo-jquery issue: https://github.com/telerik/kendo-ui-core/issues/4551.
