### ISSUE TITLE
Window's shadow is not transparent

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-theme-default#861]
Limiting a window to a specific Panel within a Splitter causes the shadow around the window to lose its transparency. When you start dragging the window the shadow is normal until you release it.

Check the following sample plunker demonstrating the issue:

[https://plnkr.co/edit/Wk5qnArvQ5D8q9oGZAnw?p=preview](https://plnkr.co/edit/Wk5qnArvQ5D8q9oGZAnw?p=preview)

Add the following CSS for a workaround:

.k-window .k-resize-handle { background-color: transparent; }

**Comment by gyoshev** [comment]
Fixed in `@progress/kendo-theme-default@2.47.2`
