### ISSUE TITLE
on initial install, semantic-release not found

### ISSUE THREAD

**Issue by mscottnelson** [telerik/kendo-theme-default#868]
To reproduce:
1) fresh clone repo
2) npm install
--> 404 Not Found: @semantic-release/condition-travis@^5.0.2

**Comment by gyoshev** [comment]
@mscottnelson we have moved the development of all themes to the [kendo-themes monorepo](https://github.com/telerik/kendo-themes), which has a different workflow and does not depend on `semantic-release`. Please give it a try, and log any issues in that repo. We are preparing this repository to be archived.
