### ISSUE TITLE
The Kendo UI Grid wrapper for React with a locked column is misaligned in an Internet Explorer 11. 

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-theme-default#869]
The Kendo UI Grid wrapper for React with a locked column is misaligned in an Internet Explorer 11. 

A runnable example can be found in the following ticket:  1151973

**Comment by joneff** [comment]
Seems to be fixed by https://github.com/telerik/kendo-themes/commit/a14a49a
