### ISSUE TITLE
Delete buttons for MultiSelect tags are not visible

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-theme-default#87]
Can be reproduced with the latest theme version. It looks like it is a regression from the clear all button style implementation.

**Comment by KirilNN** [comment]
A special class `k-clear-value` was added for both Angular and jQuery MultiSelect components, so we can use it to style the `delete all` button by itself.

**Comment by inikolova** [comment]
Great! Thank you. I will update the clear button styling.
