### ISSUE TITLE
Title of the Dialog component cuts off letters

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-theme-default#871]
Some of the letters, like "g" and "y", used within the title of a Dialog are cut off.

Check the following sample plunker demonstrating the undesired behavior:

[https://plnkr.co/edit/aO5LNgLwVM0S5Y2EoVPK?p=preview](https://plnkr.co/edit/aO5LNgLwVM0S5Y2EoVPK?p=preview)

**Comment by Abdullah0991** [comment]
Me too :( 
Any solution?

**Comment by gyoshev** [comment]
The issue has been fixed in the latest versions of the themes ([updated plunker](https://plnkr.co/edit/ZlG19lpWxzuB4hUJU56D?p=preview)).
