### ISSUE TITLE
Upgrade to 2.50.0 - Red Color on text

### ISSUE THREAD

**Issue by RafaelMontegordoFelix** [telerik/kendo-theme-default#872]
Hello,
After Upgrading to version 2.50.0, i started to get red color on some text.

I find that a new style was introduced - .ng-invalid.ng-touched>[class*=-wrap].

As i was using a class called content-wrapper in my form, so when the ng-invalid and ng-touched is set on the form, all the text become red.

![image](https://user-images.githubusercontent.com/16720099/39007230-3a9cb4bc-43fd-11e8-9321-42771445cb0a.png)

I believe that allot of people are using names that contains "-wrap" and .ng-invalid.ng-touched.,
so i know that you wouldn't put this class and break all that css.

My question is how can i use classes that contains "-wrap" and continue updating kendo ui theme package?

Thanks

**Comment by gyoshev** [comment]
Thank you for reporting this, @RafaelMontegordoFelix , we will strive to release a fix for this problem with a new version of the theme by the end of the week.

**Comment by RafaelMontegordoFelix** [comment]
Thank you very much.

**Comment by RafaelMontegordoFelix** [comment]
Hello guys, was this fix pushed to version 2.51.0?

**Comment by gyoshev** [comment]
Yes, here is a [sample that shows this](https://plnkr.co/edit/VQzE2p9Acdk6DcGSQKl4?p=preview) with the latest theme.
