### ISSUE TITLE
Add a class for the DateInput when displaying the placeholder

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-theme-default#874]
Provide a class that could be used to style the DateInput while the placeholder is displayed.

**Comment by gyoshev** [comment]
The enhancement implemented in https://github.com/telerik/kendo-angular/issues/1356 will allow the placeholder to be styled through the `::placeholder` generated element selector, and the input via the `:placeholder-shown` pseudo-class selector. See the [related CSS-Tricks article](https://css-tricks.com/almanac/selectors/p/placeholder/) for more details.
