### ISSUE TITLE
NumericTextBox spinners

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-theme-default#94]
When clicking fast on the spinners in Chrome a blue are appears
![spinners](https://cloud.githubusercontent.com/assets/11816882/21883853/915e0ce8-d8b9-11e6-9bf2-0d9e0e389cc0.jpg)

**Comment by joneff** [comment]
It's not reproducible with with kendo-jquery-numerictextbox -- http://dojo.telerik.com/@joneff/UmIKo.

While it may still exist as an issue for kend-angular-numerictextbox, it appears it's not strictly related to the styles.
