### ISSUE TITLE
Icon discrepancy when using "box-sizing: border-box"

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-theme-default#95]
Can be reproduced on K2 Docs staging, since snippets include Bootstrap now

![loading](https://cloud.githubusercontent.com/assets/730205/21884428/ef848070-d8bb-11e6-85b9-c0d07b8e4d42.png)

**Comment by Raisolution** [comment]
There is a gray background on the Upload loading icon, [reproducible here](http://kendobuild-staging.openstack.progress.com/kendo-angular-ui/components/upload/). It seems related to this issue.

**Comment by inikolova** [comment]
The _gray background issue_ was related to this one -> https://github.com/telerik/kendo-theme-default/commit/c8db0225ad7107b492353690763d13c5d32f7787
